const HERBS = [
  {
    "id": "H001",
    "name": "麻黄",
    "category": "解表药-发散风寒",
    "nature": "辛、微苦，温",
    "meridian": "肺、膀胱",
    "effect": "发汗解表，宣肺平喘，利水消肿",
    "indication": "风寒感冒，胸闷喘咳，风水浮肿",
    "source": "药典2020版 第356页",
    "source_url": "https://www.baidu.com/s?wd=麻黄+中药+药典"
  },
  {
    "id": "H002",
    "name": "桂枝",
    "category": "解表药-发散风寒",
    "nature": "辛、甘，温",
    "meridian": "心、肺、膀胱",
    "effect": "发汗解肌，温通经脉，助阳化气",
    "indication": "风寒感冒，脘腹冷痛，血寒经闭",
    "source": "药典2020版 第279页",
    "source_url": "https://www.baidu.com/s?wd=桂枝+中药+药典"
  },
  {
    "id": "H003",
    "name": "紫苏叶",
    "category": "解表药-发散风寒",
    "nature": "辛，温",
    "meridian": "肺、脾",
    "effect": "解表散寒，行气和胃",
    "indication": "风寒感冒，咳嗽呕恶，妊娠呕吐",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=紫苏叶+中药+药典"
  },
  {
    "id": "H004",
    "name": "生姜",
    "category": "解表药-发散风寒",
    "nature": "辛，微温",
    "meridian": "肺、脾、胃",
    "effect": "解表散寒，温中止呕，化痰止咳",
    "indication": "风寒感冒，胃寒呕吐，寒痰咳嗽",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=生姜+中药+药典"
  },
  {
    "id": "H005",
    "name": "防风",
    "category": "解表药-发散风寒",
    "nature": "辛、甘，微温",
    "meridian": "膀胱、肝、脾",
    "effect": "祛风解表，胜湿止痛，止痉",
    "indication": "感冒头痛，风湿痹痛，风疹瘙痒",
    "source": "药典2020版 第368页",
    "source_url": "https://www.baidu.com/s?wd=防风+中药+药典"
  },
  {
    "id": "H006",
    "name": "白芷",
    "category": "解表药-发散风寒",
    "nature": "辛，温",
    "meridian": "胃、大肠、肺",
    "effect": "解表散寒，祛风止痛，宣通鼻窍",
    "indication": "风寒感冒，头痛鼻塞，牙痛",
    "source": "药典2020版 第131页",
    "source_url": "https://www.baidu.com/s?wd=白芷+中药+药典"
  },
  {
    "id": "H007",
    "name": "细辛",
    "category": "解表药-发散风寒",
    "nature": "辛，温；有小毒",
    "meridian": "心、肺、肾",
    "effect": "祛风散寒，通窍止痛，温肺化饮",
    "indication": "风寒感冒，头痛牙痛，鼻塞流涕",
    "source": "药典2020版 第396页",
    "source_url": "https://www.baidu.com/s?wd=细辛+中药+药典"
  },
  {
    "id": "H008",
    "name": "薄荷",
    "category": "解表药-发散风热",
    "nature": "辛，凉",
    "meridian": "肺、肝",
    "effect": "疏散风热，清利头目，利咽透疹",
    "indication": "风热感冒，头痛目赤，咽喉肿痛",
    "source": "药典2020版 第346页",
    "source_url": "https://www.baidu.com/s?wd=薄荷+中药+药典"
  },
  {
    "id": "H009",
    "name": "牛蒡子",
    "category": "解表药-发散风热",
    "nature": "辛、苦，凉",
    "meridian": "肺、胃",
    "effect": "疏散风热，宣肺透疹，解毒利咽",
    "indication": "风热感冒，咽喉肿痛，麻疹不透",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=牛蒡子+中药+药典"
  },
  {
    "id": "H010",
    "name": "桑叶",
    "category": "解表药-发散风热",
    "nature": "甘、苦，寒",
    "meridian": "肺、肝",
    "effect": "疏散风热，清肺润燥，清肝明目",
    "indication": "风热感冒，肺热燥咳，目赤昏花",
    "source": "药典2020版 第547页",
    "source_url": "https://www.baidu.com/s?wd=桑叶+中药+药典"
  },
  {
    "id": "H011",
    "name": "菊花",
    "category": "解表药-发散风热",
    "nature": "甘、苦，微寒",
    "meridian": "肺、肝",
    "effect": "疏散风热，平肝明目，清热解毒",
    "indication": "风热感冒，头痛眩晕，目赤肿痛",
    "source": "药典2020版 第290页",
    "source_url": "https://www.baidu.com/s?wd=菊花+中药+药典"
  },
  {
    "id": "H012",
    "name": "柴胡",
    "category": "解表药-发散风热",
    "nature": "苦，微寒",
    "meridian": "肝、胆",
    "effect": "疏散退热，疏肝解郁，升举阳气",
    "indication": "感冒发热，寒热往来，胸胁胀痛",
    "source": "药典2020版 第561页",
    "source_url": "https://www.baidu.com/s?wd=柴胡+中药+药典"
  },
  {
    "id": "H013",
    "name": "葛根",
    "category": "解表药-发散风热",
    "nature": "甘、辛，凉",
    "meridian": "脾、胃",
    "effect": "解肌退热，生津止渴，透疹",
    "indication": "外感发热，项背强痛，麻疹不透",
    "source": "药典2020版 第318页",
    "source_url": "https://www.baidu.com/s?wd=葛根+中药+药典"
  },
  {
    "id": "H014",
    "name": "石膏",
    "category": "清热药-清热泻火",
    "nature": "甘、辛，大寒",
    "meridian": "肺、胃",
    "effect": "清热泻火，除烦止渴",
    "indication": "外感热病，高热烦渴，肺热喘咳",
    "source": "药典2020版 第557页",
    "source_url": "https://www.baidu.com/s?wd=石膏+中药+药典"
  },
  {
    "id": "H015",
    "name": "知母",
    "category": "清热药-清热泻火",
    "nature": "苦、甘，寒",
    "meridian": "肺、胃、肾",
    "effect": "清热泻火，滋阴润燥",
    "indication": "外感热病，肺热燥咳，骨蒸潮热",
    "source": "药典2020版 第559页",
    "source_url": "https://www.baidu.com/s?wd=知母+中药+药典"
  },
  {
    "id": "H016",
    "name": "栀子",
    "category": "清热药-清热泻火",
    "nature": "苦，寒",
    "meridian": "心、肺、三焦",
    "effect": "泻火除烦，清热利湿，凉血解毒",
    "indication": "热病心烦，湿热黄疸，血热吐衄",
    "source": "药典2020版 第415页",
    "source_url": "https://www.baidu.com/s?wd=栀子+中药+药典"
  },
  {
    "id": "H017",
    "name": "夏枯草",
    "category": "清热药-清热泻火",
    "nature": "辛、苦，寒",
    "meridian": "肝、胆",
    "effect": "清肝泻火，明目，散结消肿",
    "indication": "目赤肿痛，头痛眩晕，瘰疬瘿瘤",
    "source": "药典2020版 第449页",
    "source_url": "https://www.baidu.com/s?wd=夏枯草+中药+药典"
  },
  {
    "id": "H018",
    "name": "黄芩",
    "category": "清热药-清热燥湿",
    "nature": "苦，寒",
    "meridian": "肺、胆、脾、大肠、小肠",
    "effect": "清热燥湿，泻火解毒，止血安胎",
    "indication": "湿温暑湿，胸闷呕恶，肺热咳嗽",
    "source": "药典2020版 第557页",
    "source_url": "https://www.baidu.com/s?wd=黄芩+中药+药典"
  },
  {
    "id": "H019",
    "name": "黄连",
    "category": "清热药-清热燥湿",
    "nature": "苦，寒",
    "meridian": "心、脾、胃、肝、胆、大肠",
    "effect": "清热燥湿，泻火解毒",
    "indication": "湿热痞满，呕吐吞酸，高热神昏",
    "source": "药典2020版 第290页",
    "source_url": "https://www.baidu.com/s?wd=黄连+中药+药典"
  },
  {
    "id": "H020",
    "name": "黄柏",
    "category": "清热药-清热燥湿",
    "nature": "苦，寒",
    "meridian": "肾、膀胱",
    "effect": "清热燥湿，泻火除蒸，解毒疗疮",
    "indication": "湿热泻痢，带下阴痒，骨蒸劳热",
    "source": "药典2020版 第290页",
    "source_url": "https://www.baidu.com/s?wd=黄柏+中药+药典"
  },
  {
    "id": "H021",
    "name": "金银花",
    "category": "清热药-清热解毒",
    "nature": "甘，寒",
    "meridian": "肺、心、胃",
    "effect": "清热解毒，疏散风热",
    "indication": "痈肿疔疮，咽喉肿痛，风热感冒",
    "source": "药典2020版 第476页",
    "source_url": "https://www.baidu.com/s?wd=金银花+中药+药典"
  },
  {
    "id": "H022",
    "name": "连翘",
    "category": "清热药-清热解毒",
    "nature": "苦，微寒",
    "meridian": "肺、心、小肠",
    "effect": "清热解毒，消肿散结，疏散风热",
    "indication": "痈疽肿毒，风热感冒，高热烦渴",
    "source": "药典2020版 第476页",
    "source_url": "https://www.baidu.com/s?wd=连翘+中药+药典"
  },
  {
    "id": "H023",
    "name": "板蓝根",
    "category": "清热药-清热解毒",
    "nature": "苦，寒",
    "meridian": "心、胃",
    "effect": "清热解毒，凉血利咽",
    "indication": "温毒发斑，咽喉肿痛，痄腮",
    "source": "药典2020版 第356页",
    "source_url": "https://www.baidu.com/s?wd=板蓝根+中药+药典"
  },
  {
    "id": "H024",
    "name": "蒲公英",
    "category": "清热药-清热解毒",
    "nature": "苦、甘，寒",
    "meridian": "肝、胃",
    "effect": "清热解毒，消肿散结，利尿通淋",
    "indication": "痈肿疔毒，乳痈，湿热黄疸",
    "source": "药典2020版 第356页",
    "source_url": "https://www.baidu.com/s?wd=蒲公英+中药+药典"
  },
  {
    "id": "H025",
    "name": "生地黄",
    "category": "清热药-清热凉血",
    "nature": "甘，寒",
    "meridian": "心、肝、肾",
    "effect": "清热凉血，养阴生津",
    "indication": "热入营血，口干舌绛，津伤便秘",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=生地黄+中药+药典"
  },
  {
    "id": "H026",
    "name": "玄参",
    "category": "清热药-清热凉血",
    "nature": "甘、苦、咸，微寒",
    "meridian": "肺、胃、肾",
    "effect": "清热凉血，滋阴降火，解毒散结",
    "indication": "热入营血，目赤咽痛，瘰疬",
    "source": "药典2020版 第249页",
    "source_url": "https://www.baidu.com/s?wd=玄参+中药+药典"
  },
  {
    "id": "H027",
    "name": "牡丹皮",
    "category": "清热药-清热凉血",
    "nature": "苦、辛，微寒",
    "meridian": "心、肝、肾",
    "effect": "清热凉血，活血化瘀",
    "indication": "热入营血，温毒发斑，经闭痛经",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=牡丹皮+中药+药典"
  },
  {
    "id": "H028",
    "name": "青蒿",
    "category": "清热药-清虚热",
    "nature": "苦、辛，寒",
    "meridian": "肝、胆",
    "effect": "清虚热，除骨蒸，解暑，截疟",
    "indication": "温邪伤阴，夜热早凉，暑邪发热",
    "source": "药典2020版 第449页",
    "source_url": "https://www.baidu.com/s?wd=青蒿+中药+药典"
  },
  {
    "id": "H029",
    "name": "地骨皮",
    "category": "清热药-清虚热",
    "nature": "甘，寒",
    "meridian": "肺、肝、肾",
    "effect": "凉血除蒸，清肺降火",
    "indication": "阴虚潮热，骨蒸盗汗，肺热咳喘",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=地骨皮+中药+药典"
  },
  {
    "id": "H030",
    "name": "大黄",
    "category": "泻下药-攻下药",
    "nature": "苦，寒",
    "meridian": "脾、胃、大肠、肝、心包",
    "effect": "泻下攻积，清热泻火，凉血解毒",
    "indication": "实热积滞便秘，血热吐衄，目赤咽痛",
    "source": "药典2020版 第22页",
    "source_url": "https://www.baidu.com/s?wd=大黄+中药+药典"
  },
  {
    "id": "H031",
    "name": "芒硝",
    "category": "泻下药-攻下药",
    "nature": "咸、苦，寒",
    "meridian": "胃、大肠",
    "effect": "泻下通便，润燥软坚，清火消肿",
    "indication": "实热积滞便秘，咽痛口疮，目赤",
    "source": "药典2020版 第441页",
    "source_url": "https://www.baidu.com/s?wd=芒硝+中药+药典"
  },
  {
    "id": "H032",
    "name": "独活",
    "category": "祛风湿药",
    "nature": "辛、苦，微温",
    "meridian": "肾、膀胱",
    "effect": "祛风除湿，通痹止痛",
    "indication": "风寒湿痹，腰膝疼痛，头痛",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=独活+中药+药典"
  },
  {
    "id": "H033",
    "name": "威灵仙",
    "category": "祛风湿药",
    "nature": "辛、咸，温",
    "meridian": "膀胱",
    "effect": "祛风湿，通经络，止痹痛",
    "indication": "风湿痹痛，肢体麻木，筋脉拘挛",
    "source": "药典2020版 第397页",
    "source_url": "https://www.baidu.com/s?wd=威灵仙+中药+药典"
  },
  {
    "id": "H034",
    "name": "桑寄生",
    "category": "祛风湿药",
    "nature": "苦、甘，平",
    "meridian": "肝、肾",
    "effect": "祛风湿，补肝肾，强筋骨",
    "indication": "风湿痹痛，腰膝酸软，崩漏经多",
    "source": "药典2020版 第549页",
    "source_url": "https://www.baidu.com/s?wd=桑寄生+中药+药典"
  },
  {
    "id": "H035",
    "name": "藿香",
    "category": "化湿药",
    "nature": "辛，微温",
    "meridian": "脾、胃、肺",
    "effect": "芳香化浊，和中止呕，发表解暑",
    "indication": "湿浊中阻，脘痞呕吐，暑湿表证",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=藿香+中药+药典"
  },
  {
    "id": "H036",
    "name": "苍术",
    "category": "化湿药",
    "nature": "辛、苦，温",
    "meridian": "脾、胃、肝经",
    "effect": "燥湿健脾，祛风散寒，明目",
    "indication": "湿阻中焦，脘腹胀满，风湿痹痛",
    "source": "药典2020版 第279页",
    "source_url": "https://www.baidu.com/s?wd=苍术+中药+药典"
  },
  {
    "id": "H037",
    "name": "厚朴",
    "category": "化湿药",
    "nature": "苦、辛，温",
    "meridian": "脾、胃、肺、大肠",
    "effect": "燥湿消痰，下气除满",
    "indication": "湿滞伤中，脘痞吐泻，痰饮喘咳",
    "source": "药典2020版 第448页",
    "source_url": "https://www.baidu.com/s?wd=厚朴+中药+药典"
  },
  {
    "id": "H038",
    "name": "茯苓",
    "category": "利水渗湿药",
    "nature": "甘、淡，平",
    "meridian": "心、肺、脾、肾",
    "effect": "利水渗湿，健脾，宁心",
    "indication": "水肿尿少，痰饮眩悸，脾虚食少",
    "source": "药典2020版 第557页",
    "source_url": "https://www.baidu.com/s?wd=茯苓+中药+药典"
  },
  {
    "id": "H039",
    "name": "薏苡仁",
    "category": "利水渗湿药",
    "nature": "甘、淡，凉",
    "meridian": "脾、胃、肺",
    "effect": "利水渗湿，健脾止泻，除痹排脓",
    "indication": "水肿，脚气，脾虚泄泻，湿痹拘挛",
    "source": "药典2020版 第539页",
    "source_url": "https://www.baidu.com/s?wd=薏苡仁+中药+药典"
  },
  {
    "id": "H040",
    "name": "泽泻",
    "category": "利水渗湿药",
    "nature": "甘、淡，寒",
    "meridian": "肾、膀胱",
    "effect": "利水渗湿，泄热，化浊降脂",
    "indication": "小便不利，水肿胀满，痰饮眩晕",
    "source": "药典2020版 第441页",
    "source_url": "https://www.baidu.com/s?wd=泽泻+中药+药典"
  },
  {
    "id": "H041",
    "name": "车前子",
    "category": "利水渗湿药",
    "nature": "甘，微寒",
    "meridian": "肝、肾、肺、小肠",
    "effect": "清热利尿，渗湿通淋，明目祛痰",
    "indication": "热淋涩痛，水肿胀满，目赤肿痛",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=车前子+中药+药典"
  },
  {
    "id": "H042",
    "name": "茵陈",
    "category": "利水渗湿药",
    "nature": "苦、辛，微寒",
    "meridian": "脾、胃、肝、胆",
    "effect": "清利湿热，利胆退黄",
    "indication": "黄疸尿少，湿温暑湿，湿疮瘙痒",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=茵陈+中药+药典"
  },
  {
    "id": "H043",
    "name": "附子",
    "category": "温里药",
    "nature": "辛、甘，大热；有毒",
    "meridian": "心、肾、脾",
    "effect": "回阳救逆，补火助阳，散寒止痛",
    "indication": "亡阳虚脱，肢冷脉微，心阳不足",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=附子+中药+药典"
  },
  {
    "id": "H044",
    "name": "干姜",
    "category": "温里药",
    "nature": "辛，热",
    "meridian": "脾、胃、肾、心、肺",
    "effect": "温中散寒，回阳通脉，温肺化饮",
    "indication": "脘腹冷痛，呕吐泄泻，亡阳厥逆",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=干姜+中药+药典"
  },
  {
    "id": "H045",
    "name": "肉桂",
    "category": "温里药",
    "nature": "辛、甘，大热",
    "meridian": "肾、脾、心、肝",
    "effect": "补火助阳，引火归元，散寒止痛",
    "indication": "阳痿宫冷，腰膝冷痛，阳虚眩晕",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=肉桂+中药+药典"
  },
  {
    "id": "H046",
    "name": "吴茱萸",
    "category": "温里药",
    "nature": "辛、苦，热；有小毒",
    "meridian": "肝、脾、胃、肾",
    "effect": "散寒止痛，降逆止呕，助阳止泻",
    "indication": "厥阴头痛，寒疝腹痛，寒湿泄泻",
    "source": "药典2020版 第397页",
    "source_url": "https://www.baidu.com/s?wd=吴茱萸+中药+药典"
  },
  {
    "id": "H047",
    "name": "陈皮",
    "category": "理气药",
    "nature": "苦、辛，温",
    "meridian": "肺、脾",
    "effect": "理气健脾，燥湿化痰",
    "indication": "脘腹胀满，食少吐泻，咳嗽痰多",
    "source": "药典2020版 第605页",
    "source_url": "https://www.baidu.com/s?wd=陈皮+中药+药典"
  },
  {
    "id": "H048",
    "name": "枳实",
    "category": "理气药",
    "nature": "苦、辛、酸，微寒",
    "meridian": "脾、胃",
    "effect": "破气消积，化痰散痞",
    "indication": "积滞内停，痞满胀痛，痰滞气阻",
    "source": "药典2020版 第476页",
    "source_url": "https://www.baidu.com/s?wd=枳实+中药+药典"
  },
  {
    "id": "H049",
    "name": "木香",
    "category": "理气药",
    "nature": "辛、苦，温",
    "meridian": "脾、胃、大肠、三焦、胆",
    "effect": "行气止痛，健脾消食",
    "indication": "胸胁脘腹胀痛，泻痢后重，食积不消",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=木香+中药+药典"
  },
  {
    "id": "H050",
    "name": "香附",
    "category": "理气药",
    "nature": "辛、微苦、微甘，平",
    "meridian": "肝、脾、三焦",
    "effect": "疏肝解郁，理气宽中，调经止痛",
    "indication": "肝郁气滞，胸胁胀痛，月经不调",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=香附+中药+药典"
  },
  {
    "id": "H051",
    "name": "山楂",
    "category": "消食药",
    "nature": "酸、甘，微温",
    "meridian": "脾、胃、肝经",
    "effect": "消食健胃，行气散瘀，化浊降脂",
    "indication": "肉食积滞，胃脘胀满，瘀血经闭",
    "source": "药典2020版 第24页",
    "source_url": "https://www.baidu.com/s?wd=山楂+中药+药典"
  },
  {
    "id": "H052",
    "name": "神曲",
    "category": "消食药",
    "nature": "甘、辛，温",
    "meridian": "脾、胃",
    "effect": "消食和胃",
    "indication": "饮食积滞，消化不良，脘腹胀满",
    "source": "中药学教材（第十版）",
    "source_url": "https://www.baidu.com/s?wd=神曲+中药+药典"
  },
  {
    "id": "H053",
    "name": "麦芽",
    "category": "消食药",
    "nature": "甘，平",
    "meridian": "脾、胃、肝",
    "effect": "行气消食，健脾开胃，回乳消胀",
    "indication": "食积不消，脘腹胀痛，乳汁郁积",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=麦芽+中药+药典"
  },
  {
    "id": "H054",
    "name": "小蓟",
    "category": "止血药",
    "nature": "甘、苦，凉",
    "meridian": "心、肝经",
    "effect": "凉血止血，散瘀解毒消痈",
    "indication": "血热出血，痈肿疮毒",
    "source": "药典2020版 第68页",
    "source_url": "https://www.baidu.com/s?wd=小蓟+中药+药典"
  },
  {
    "id": "H055",
    "name": "地榆",
    "category": "止血药",
    "nature": "苦、酸、涩，微寒",
    "meridian": "肝、大肠",
    "effect": "凉血止血，解毒敛疮",
    "indication": "血热出血，疮疡肿毒，湿疹",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=地榆+中药+药典"
  },
  {
    "id": "H056",
    "name": "三七",
    "category": "止血药",
    "nature": "甘、微苦，温",
    "meridian": "肝、胃",
    "effect": "散瘀止血，消肿定痛",
    "indication": "咯血衄血，跌打损伤，瘀血肿痛",
    "source": "药典2020版 第10页",
    "source_url": "https://www.baidu.com/s?wd=三七+中药+药典"
  },
  {
    "id": "H057",
    "name": "川芎",
    "category": "活血化瘀药",
    "nature": "辛，温",
    "meridian": "肝、胆、心包",
    "effect": "活血行气，祛风止痛",
    "indication": "胸痹心痛，胸胁刺痛，头痛，风湿痹痛",
    "source": "药典2020版 第68页",
    "source_url": "https://www.baidu.com/s?wd=川芎+中药+药典"
  },
  {
    "id": "H058",
    "name": "延胡索",
    "category": "活血化瘀药",
    "nature": "辛、苦，温",
    "meridian": "肝、脾",
    "effect": "活血，行气，止痛",
    "indication": "胸胁脘腹疼痛，胸痹心痛，痛经",
    "source": "药典2020版 第249页",
    "source_url": "https://www.baidu.com/s?wd=延胡索+中药+药典"
  },
  {
    "id": "H059",
    "name": "郁金",
    "category": "活血化瘀药",
    "nature": "辛、苦，寒",
    "meridian": "肝、心、肺",
    "effect": "活血止痛，行气解郁，清心凉血",
    "indication": "胸胁刺痛，胸痹心痛，经闭痛经",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=郁金+中药+药典"
  },
  {
    "id": "H060",
    "name": "丹参",
    "category": "活血化瘀药",
    "nature": "苦，微寒",
    "meridian": "心、肝经",
    "effect": "活血祛瘀，通经止痛，清心除烦",
    "indication": "胸痹心痛，心烦不眠，月经不调",
    "source": "药典2020版 第68页",
    "source_url": "https://www.baidu.com/s?wd=丹参+中药+药典"
  },
  {
    "id": "H061",
    "name": "红花",
    "category": "活血化瘀药",
    "nature": "辛，温",
    "meridian": "心、肝经",
    "effect": "活血通经，散瘀止痛",
    "indication": "经闭痛经，胸痹心痛，跌打损伤",
    "source": "药典2020版 第193页",
    "source_url": "https://www.baidu.com/s?wd=红花+中药+药典"
  },
  {
    "id": "H062",
    "name": "桃仁",
    "category": "活血化瘀药",
    "nature": "苦、甘，平",
    "meridian": "心、肝、大肠",
    "effect": "活血祛瘀，润肠通便，止咳平喘",
    "indication": "经闭痛经，癥瘕痞块，肺痈肠痈",
    "source": "药典2020版 第476页",
    "source_url": "https://www.baidu.com/s?wd=桃仁+中药+药典"
  },
  {
    "id": "H063",
    "name": "益母草",
    "category": "活血化瘀药",
    "nature": "苦、辛，微寒",
    "meridian": "肝、心包、膀胱",
    "effect": "活血调经，利尿消肿，清热解毒",
    "indication": "月经不调，痛经经闭，水肿尿少",
    "source": "药典2020版 第539页",
    "source_url": "https://www.baidu.com/s?wd=益母草+中药+药典"
  },
  {
    "id": "H064",
    "name": "半夏",
    "category": "化痰止咳平喘药",
    "nature": "辛，温；有毒",
    "meridian": "脾、胃、肺",
    "effect": "燥湿化痰，降逆止呕，消痞散结",
    "indication": "湿痰寒痰，咳喘痰多，痰饮眩悸",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=半夏+中药+药典"
  },
  {
    "id": "H065",
    "name": "川贝母",
    "category": "化痰止咳平喘药",
    "nature": "苦、甘，微寒",
    "meridian": "肺、心",
    "effect": "清热润肺，化痰止咳，散结消痈",
    "indication": "肺热燥咳，干咳少痰，乳痈",
    "source": "药典2020版 第68页",
    "source_url": "https://www.baidu.com/s?wd=川贝母+中药+药典"
  },
  {
    "id": "H066",
    "name": "瓜蒌",
    "category": "化痰止咳平喘药",
    "nature": "甘、微苦，寒",
    "meridian": "肺、胃、大肠",
    "effect": "清热涤痰，宽胸散结，润燥滑肠",
    "indication": "肺热咳嗽，痰浊黄稠，胸痹心痛",
    "source": "药典2020版 第318页",
    "source_url": "https://www.baidu.com/s?wd=瓜蒌+中药+药典"
  },
  {
    "id": "H067",
    "name": "杏仁",
    "category": "化痰止咳平喘药",
    "nature": "苦，微温；有小毒",
    "meridian": "肺、大肠",
    "effect": "降气止咳平喘，润肠通便",
    "indication": "咳嗽气喘，胸满痰多，肠燥便秘",
    "source": "药典2020版 第476页",
    "source_url": "https://www.baidu.com/s?wd=杏仁+中药+药典"
  },
  {
    "id": "H068",
    "name": "紫苏子",
    "category": "化痰止咳平喘药",
    "nature": "辛，温",
    "meridian": "肺、大肠",
    "effect": "降气化痰，止咳平喘，润肠通便",
    "indication": "痰壅气逆，咳嗽气喘，肠燥便秘",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=紫苏子+中药+药典"
  },
  {
    "id": "H069",
    "name": "酸枣仁",
    "category": "安神药",
    "nature": "甘、酸，平",
    "meridian": "心、肝、胆",
    "effect": "养心补肝，宁心安神，敛汗",
    "indication": "虚烦不眠，惊悸多梦，体虚多汗",
    "source": "药典2020版 第605页",
    "source_url": "https://www.baidu.com/s?wd=酸枣仁+中药+药典"
  },
  {
    "id": "H070",
    "name": "远志",
    "category": "安神药",
    "nature": "苦、辛，温",
    "meridian": "心、肾、肺",
    "effect": "安神益智，交通心肾，祛痰开窍",
    "indication": "心肾不交，失眠多梦，健忘惊悸",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=远志+中药+药典"
  },
  {
    "id": "H071",
    "name": "石决明",
    "category": "平肝息风药",
    "nature": "咸，寒",
    "meridian": "肝",
    "effect": "平肝潜阳，清肝明目",
    "indication": "头痛眩晕，目赤翳障，视物昏花",
    "source": "药典2020版 第193页",
    "source_url": "https://www.baidu.com/s?wd=石决明+中药+药典"
  },
  {
    "id": "H072",
    "name": "天麻",
    "category": "平肝息风药",
    "nature": "甘，平",
    "meridian": "肝",
    "effect": "息风止痉，平抑肝阳，祛风通络",
    "indication": "小儿惊风，头痛眩晕，手足不遂",
    "source": "药典2020版 第68页",
    "source_url": "https://www.baidu.com/s?wd=天麻+中药+药典"
  },
  {
    "id": "H073",
    "name": "钩藤",
    "category": "平肝息风药",
    "nature": "甘，凉",
    "meridian": "肝、心包",
    "effect": "息风定惊，清热平肝",
    "indication": "头痛眩晕，惊厥抽搐，妊娠子痫",
    "source": "药典2020版 第442页",
    "source_url": "https://www.baidu.com/s?wd=钩藤+中药+药典"
  },
  {
    "id": "H074",
    "name": "人参",
    "category": "补虚药-补气",
    "nature": "甘、微苦，微温",
    "meridian": "脾、肺、心、肾",
    "effect": "大补元气，复脉固脱，补脾益肺",
    "indication": "体虚欲脱，肢冷脉微，脾虚食少",
    "source": "药典2020版 第2页",
    "source_url": "https://www.baidu.com/s?wd=人参+中药+药典"
  },
  {
    "id": "H075",
    "name": "黄芪",
    "category": "补虚药-补气",
    "nature": "甘，微温",
    "meridian": "肺、脾",
    "effect": "补气升阳，固表止汗，利水消肿",
    "indication": "气虚乏力，食少便溏，中气下陷",
    "source": "药典2020版 第356页",
    "source_url": "https://www.baidu.com/s?wd=黄芪+中药+药典"
  },
  {
    "id": "H076",
    "name": "白术",
    "category": "补虚药-补气",
    "nature": "苦、甘，温",
    "meridian": "脾、胃",
    "effect": "健脾益气，燥湿利水，止汗安胎",
    "indication": "脾虚食少，腹胀泄泻，痰饮眩悸",
    "source": "药典2020版 第248页",
    "source_url": "https://www.baidu.com/s?wd=白术+中药+药典"
  },
  {
    "id": "H077",
    "name": "甘草",
    "category": "补虚药-补气",
    "nature": "甘，平",
    "meridian": "心、肺、脾、胃",
    "effect": "补脾益气，清热解毒，祛痰止咳，调和诸药",
    "indication": "脾胃虚弱，倦怠乏力，咳嗽痰多",
    "source": "药典2020版 第92页",
    "source_url": "https://www.baidu.com/s?wd=甘草+中药+药典"
  },
  {
    "id": "H078",
    "name": "当归",
    "category": "补虚药-补血",
    "nature": "甘、辛，温",
    "meridian": "肝、心、脾",
    "effect": "补血活血，调经止痛，润肠通便",
    "indication": "血虚萎黄，眩晕心悸，月经不调",
    "source": "药典2020版 第193页",
    "source_url": "https://www.baidu.com/s?wd=当归+中药+药典"
  },
  {
    "id": "H079",
    "name": "熟地黄",
    "category": "补虚药-补血",
    "nature": "甘，微温",
    "meridian": "肝、肾",
    "effect": "补血滋阴，益精填髓",
    "indication": "血虚萎黄，肝肾阴虚，腰膝酸软",
    "source": "药典2020版 第318页",
    "source_url": "https://www.baidu.com/s?wd=熟地黄+中药+药典"
  },
  {
    "id": "H080",
    "name": "白芍",
    "category": "补虚药-补血",
    "nature": "苦、酸，微寒",
    "meridian": "肝、脾",
    "effect": "养血调经，敛阴止汗，柔肝止痛",
    "indication": "血虚萎黄，月经不调，胁痛腹痛",
    "source": "药典2020版 第130页",
    "source_url": "https://www.baidu.com/s?wd=白芍+中药+药典"
  }
];